#!/bin/bash

# requires: autoconf, libtool, libreadline-dev

tee -a /etc/ld.so.conf << ‘EOF’
/root/calvin/ext/zeromq/src/.libs
/root/calvin/ext/protobuf/src/.libs
/root/calvin/ext/googletest/src/.libs
/root/calvin/ext/zookeeper/.libs
EOF
