#!/bin/bash

# requires: autoconf, libtool, libreadline-dev

apt-get update
apt install -y pkg-config m4 libtool automake autoconf vim git openssh-server zip make cmake g++ libtool  libreadline-dev curl unzip gcc net-tools uuid-dev

mkdir ext
cd ext

#zookeeper
wget http://apache.mirrors.tds.net/zookeeper/current/zookeeper-3.4.6.tar.gz
tar xzf zookeeper-3.4.6.tar.gz
rm zookeeper-3.4.6.tar.gz
mv zookeeper-3.4.6/src/c zookeeper
rm -fr zookeeper-3.4.6
cd zookeeper
./configure --prefix=$PWD
make -j
cd ..

# protobuf
svn checkout http://protobuf.googlecode.com/svn/trunk/ protobuf
cd protobuf
./autogen.sh
./configure --prefix=$PWD
make -j
cd ..

# googletest
wget https://github.com/google/googletest/archive/release-1.6.0.zip
unzip release-1.6.0.zip
rm release-1.6.0.zip
mv googletest-release-1.6.0 googletest
cd googletest
autoreconf --install
./configure --prefix=$PWD
make -j
cd ..


# zeromq
wget http://download.zeromq.org/zeromq-2.1.11.tar.gz
tar xzf zeromq-2.1.11.tar.gz
rm zeromq-2.1.11.tar.gz
mv zeromq-2.1.11 zeromq
cd zeromq
./autogen.sh
./configure --prefix=$PWD
make -j
make install
cd ..


tee -a /etc/ld.so.conf << "EOF"
/root/calvin/ext/zeromq/src/.libs
/root/calvin/ext/protobuf/src/.libs
/root/calvin/ext/googletest/src/.libs
/root/calvin/ext/zookeeper/.libs
EOF

ldconfig
